### ISSUE TITLE
Avoid loading all the siblings when adding a node

### ISSUE THREAD

**Issue by akira28** [jackalope/jackalope-doctrine-dbal#332]
As far as I understand, each time I add a node, the library loads all the children of the parent.
Is there a way to avoid it?

**Comment by dbu** [comment]
in general, this is something to improve the performance by reducing the number of database calls. you can control how deep you want to pre-fetch by calling `$session->setFetchDepth(0)` (or other numbers). if you are using symfony and the doctrine/phpcr-odm-bundle, use 
```
doctrine_phpcr:
    session:
        ...
        options:
            jackalope.fetch_depth: 1
```
